export const ACTION_TYPE = {
	CATEGORY_SIDE_MENU: 'CATEGORY_SIDE_MENU',
	GET_LOADING_PRODUCTS: 'SET_LOADING_PRODUCTS',
	GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
	SET_CATEGORY: 'SET_CATEGORY',
	GET_INPUT_SEARCH: 'GET_INPUT_SEARCH',
	GET_PRODUCT: 'GET_PRODUCT',
	ADD_PRODUCT_BASKET: 'GET_PRODUCT_BASKET',
	INPUT_COUNTER: 'INPUT_COUNTER',
	UPDATE_INPUT_PLUS: 'INPUT_COUNTER',
	UPDATE_INPUT_MINUS: 'UPDATE_INPUT_MINUS',
	UPDATE_INPUT: 'UPDATE_INPUT',
};
