export const ACTION_TYPE = {
	CATEGORY_SIDE_MENU: 'CATEGORY_SIDE_MENU',
	GET_LOADING_PRODUCTS: 'SET_LOADING_PRODUCTS',
	GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
	SET_CATEGORY: 'SET_CATEGORY',
	GET_INPUT_SEARCH: 'GET_INPUT_SEARCH',
};
